---
title: "Using Spatial Lag, Spatial Error and Geographically Weighted Regression to Predict Median House Values in Philadelphia Block Groups"
author: "Emily Zhou, Ziyi Guo, Emma Jiang"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: simplex
    toc: yes
    toc_float: yes
    code_folding: hide
    code_download: yes
bibliography: references.bib
csl: apa.csl 

editor_options:
  markdown:
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

options(scipen = 999)

library(tidyverse)
library(sf)
library(here)
library(spdep)
library(spgwr)
library(spatialreg)
library(whitestrap)
library(lmtest)
library(tseries)
library(ggplot2)

```


```{r}

regData <- st_read(here("data", "RegressionData.shp"))

```


```{r}
# check for queen neighbors
queen<-poly2nb(regData, row.names=regData$POLY_ID)
summary(queen)
```

```{r}

# global moran I

queenlist<-nb2listw(queen, style = 'W')
observed_moran <- moran(regData$LNMEDHVAL, queenlist, n=length(queenlist$neighbours), S0=Szero(queenlist))$`I` 
observed_moran
```


```{r}

moranMC<-moran.mc(regData$LNMEDHVAL, queenlist, nsim=999, alternative="two.sided") 
moranMC

```

```{r}


moranMC_df <- data.frame(moranMCres = moranMC$res)

ggplot(moranMC_df, aes(x = moranMC$res)) +
  geom_histogram(bins = 100, fill = 'blue', color = 'black', alpha = 0.7) +
  geom_vline(xintercept = observed_moran, color = 'red', linetype = 'dashed', size = 1.2) +
  labs(title = "Distribution of Moran's I from Random Permutations",
       x = "Moran's I",
       y = "Frequency") +
  theme_minimal()

```

```{r}

spatial_lag <- lag.listw(queenlist, regData$LNMEDHVAL)

# Create a data frame with the variable and its spatial lag
moran_df <- data.frame(
  LNMEDHVAL = regData$LNMEDHVAL,
  spatial_lag = spatial_lag
)

# Plot using ggplot
ggplot(moran_df, aes(x = LNMEDHVAL, y = spatial_lag)) +
  geom_point(color = "blue", alpha = 0.7) +  # Scatter plot points
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Linear regression line
  labs(title = "Moran Scatter Plot",
       x = "LNMEDHVAL",
       y = "Spatial Lag of LNMEDHVAL") +
  theme_minimal()
```



```{r}

# local moran's I

LISA<-localmoran(regData$LNMEDHVAL , queenlist)
head(LISA)

```
```{r}
df.LISA <-cbind(shp, as.data.frame(LISA))

```

```{r}

# OLS regression

OLS <- lm(LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, data=regData)
summary(OLS)
```

```{r}

fitted_values <- fitted(OLS)
residuals_values <- residuals(OLS)
standardized_residuals <- rstandard(OLS)
resnb<-sapply(queen, function(x) mean(standardized_residuals[x]))
regData <- regData %>%
  mutate(
    Fitted = fitted_values,
    Residuals = residuals_values,
    Standardized_Residuals = standardized_residuals,
    Residuals_NB = resnb)

```


```{r}

#Regressing residuals on their nearest neighbors.
res.lm <- lm(Standardized_Residuals ~ Residuals_NB, data=regData)
summary(res.lm)

```

```{r}
ggplot(regData, aes(x = Residuals_NB, y = Standardized_Residuals)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(title = "Residuals vs. Nearest Neighbor Residuals",
       x = "Nearest Neighbor Residuals",
       y = "Standardized Residuals") +
  theme_minimal()
```

```{r}

# Moran’s I of the OLS regression residuals
residuals_moran <- moran(standardized_residuals, queenlist, n=length(queenlist$neighbours), S0=Szero(queenlist))$`I`
residuals_moran

res_moranMC<-moran.mc(standardized_residuals, queenlist, nsim=999, alternative="two.sided") 
res_moranMC
```


```{r}

res_moranMC_df <- data.frame(res_moranMCres = res_moranMC$res)

ggplot(res_moranMC_df, aes(x = res_moranMC$res)) +
  geom_histogram(bins = 100, fill = 'blue', color = 'black', alpha = 0.7) +
  geom_vline(xintercept = residuals_moran, color = 'red', linetype = 'dashed', size = 1.2) +
  labs(title = "Distribution of Moran's I from Random Permutations",
       x = "Moran's I",
       y = "Frequency") +
  theme_minimal()
```


```{r}

res_spatial_lag <- lag.listw(queenlist, standardized_residuals)

# Create a data frame with the variable and its spatial lag
res_moran_df <- data.frame(
  residuals =standardized_residuals,
  spatial_lag = res_spatial_lag
)

# Plot using ggplot
ggplot(res_moran_df, aes(x = residuals, y = spatial_lag)) +
  geom_point(color = "blue", alpha = 0.7) +  # Scatter plot points
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Linear regression line
  labs(title = "Moran Scatter Plot",
       x = "LNMEDHVAL",
       y = "Spatial Lag of LNMEDHVAL") +
  theme_minimal()


```

```{r}

# running spatial lag regression 

SL <- lagsarlm(LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, data=regData, queenlist)
summary(SL)

```


```{r}

SL_res<-SL$residuals

SL_resMoran<-moran(SL_res, queenlist, n=length(queenlist$neighbours), S0=Szero(queenlist))$`I`
SL_resMoran
SL_resMoranMc<-moran.mc(SL_res, queenlist,999, alternative="two.sided")
SL_resMoranMc

```

```{r}

SL_spatial_lag <- lag.listw(queenlist, SL_res)

# Create a data frame with the variable and its spatial lag
SL_moran_df <- data.frame(
  residuals =SL_res,
  spatial_lag = SL_spatial_lag
)

# Plot using ggplot
ggplot(SL_moran_df, aes(x = residuals, y = spatial_lag)) +
  geom_point(color = "blue", alpha = 0.7) +  # Scatter plot points
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Linear regression line
  labs(title = "Moran Scatter Plot",
       x = "LNMEDHVAL",
       y = "Spatial Lag of LNMEDHVAL") +
  theme_minimal()

```
```{r}

# running spatial error regression

SE <- errorsarlm(LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, data=regData, queenlist)
summary(SE)
```


```{r}

SE_res<-residuals(SE)
SE_resMoranMc<-moran.mc(SE_res, queenlist, 999, alternative="two.sided")
SE_resMoranMc
```

```{r}

SE_spatial_lag <- lag.listw(queenlist, SE_res)

# Create a data frame with the variable and its spatial lag
SE_moran_df <- data.frame(
  residuals =SE_res,
  spatial_lag = SE_spatial_lag
)

# Plot using ggplot
ggplot(SE_moran_df, aes(x = residuals, y = spatial_lag)) +
  geom_point(color = "blue", alpha = 0.7) +  # Scatter plot points
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Linear regression line
  labs(title = "Moran Scatter Plot",
       x = "LNMEDHVAL",
       y = "Spatial Error of LNMEDHVAL") +
  theme_minimal()

```

```{r}

# running GWR

shps <- as(regData, 'Spatial')  
class (shps)

```



```{r}

bw<-gwr.sel(formula=LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, 
            data=shps,
            method = "aic",
            adapt = TRUE)
bw
```

```{r}

bw_fixed<-gwr.sel(formula=LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, 
            data=shps,
            method = "aic",
            adapt = FALSE)
bw_fixed
```


```{r}
gwrmodel<-gwr(formula=LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV,
              data=shps,
              adapt = bw, #adaptive bandwidth determined by proportion of observations accounted for
              gweight=gwr.Gauss,
              se.fit=TRUE, #to return local standard errors
              hatmatrix = TRUE)
gwrmodel
```


```{r}

gwrmodel_fixed<-gwr(formula=LNMEDHVAL ~ PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV,
              data=shps,
              bandwidth = bw_fixed, #fixed bandwidth
              gweight=gwr.Gauss,
              se.fit=TRUE, #to return local standard errors
              hatmatrix = TRUE)
gwrmodel_fixed

```

```{r}

summary(gwrmodel$SDF)

```

```{r}

gwrresults<-as.data.frame(gwrmodel$SDF)
shps$localR2<-gwrresults$localR2

```

```{r}


shps_sf <- st_as_sf(shps)
# Plot the choropleth map
ggplot(data = shps_sf) +
  geom_sf(aes(fill = localR2), color = NA) +  # Use the localR2 for the fill
  scale_fill_gradientn(
    colors = RColorBrewer::brewer.pal(9, "Reds"),   # 'Blues' palette from RColorBrewer
    breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9), # Define custom breaks
    limits = c(0, 0.9),   # Limit the scale between 0 and 0.7
    name = "Local R-Squared"  # Label the legend
  ) +
  theme_minimal() +  # Minimal theme for clean presentation
  labs(title = "Local R-Squared from GWR", x = "", y = "") +  # Add a title
  theme(legend.position = "right",  # Position the legend on the right
        panel.grid.major = element_blank(),  # Remove grid lines for a clean look
        panel.background = element_blank())  # Remove background

```


```{r}

gwr_residuals <- gwrresults$gwr.e
gwr_resMoranMc<-moran.mc(gwr_residuals, queenlist, 999, alternative="two.sided")
gwr_resMoranMc
```

```{r}

gwr_spatial_lag <- lag.listw(queenlist, gwr_residuals)

# Create a data frame with the variable and its spatial lag
gwr_moran_df <- data.frame(
  residuals = gwr_residuals,
  spatial_lag = gwr_spatial_lag
)

# Plot using ggplot
ggplot(gwr_moran_df, aes(x = residuals, y = spatial_lag)) +
  geom_point(color = "blue", alpha = 0.7) +  # Scatter plot points
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Linear regression line
  labs(title = "Moran Scatter Plot",
       x = "LNMEDHVAL",
       y = "Spatial Lagged of LNMEDHVAL") +
  theme_minimal()



```

```{r}

gwr_moranMC_df <- data.frame(gwr_resMoranMc = gwr_resMoranMc$res)


ggplot(gwr_moranMC_df, aes(x = gwr_resMoranMc)) +
  geom_histogram(bins = 100, fill = 'blue', color = 'black', alpha = 0.7) +
  geom_vline(xintercept = 0.033425 , color = 'red', linetype = 'dashed', size = 1.2) +
  labs(title = "Distribution of Moran's I from Random Permutations",
       x = "Moran's I",
       y = "Frequency") +
  theme_minimal()

```

```{r}
# present maps of the ratio of the beta coefficients and the standard error estimates. 
# Use dark red when the ratio is < - 2, pink when the ratio is between 0 and -2, light blue when the ratio is between 0 and 2, and dark blue when the ratio is > 2.


shps$coefPCTVACANTst<-gwrresults$PCTVACANT/gwrresults$PCTVACANT_se
shps$coefPCTSINGLESst<-gwrresults$PCTSINGLES/gwrresults$PCTSINGLES_se
shps$coefPCTBACHMORst<-gwrresults$PCTBACHMOR/gwrresults$PCTBACHMOR_se
shps$coefLNNBELPOVst<-gwrresults$LNNBELPOV/gwrresults$LNNBELPOV_se

shps_sf <- st_as_sf(shps)


```


```{r}

# Categorize the standardized coefficient using cut
shps_sf$coefPCTVACANTst_cat <- cut(shps_sf$coefPCTVACANTst, 
                                   breaks = c(-Inf, -2, 0, 2, Inf), 
                                   labels = c("< -2", "-2 to 0", "0 to 2", "> 2"))
shps_sf$coefPCTSINGLESst_cat <- cut(shps_sf$coefPCTSINGLESst, 
                                   breaks = c(-Inf, -2, 0, 2, Inf), 
                                   labels = c("< -2", "-2 to 0", "0 to 2", "> 2"))

shps_sf$coefPCTBACHMORst_cat <- cut(shps_sf$coefPCTBACHMORst,
                                   breaks = c(-Inf, -2, 0, 2, Inf), 
                                   labels = c("< -2", "-2 to 0", "0 to 2", "> 2"))

shps_sf$coefLNNBELPOVst_cat <- cut(shps_sf$coefLNNBELPOVst,
                                   breaks = c(-Inf, -2, 0, 2, Inf), 
                                   labels = c("< -2", "-2 to 0", "0 to 2", "> 2"))




# Plot the categorized data
ggplot(shps_sf) +
    geom_sf(aes(fill = coefPCTVACANTst_cat), color = NA) +  # Use the categorized variable
    scale_fill_manual(
      values = c("darkred", "pink", "lightblue", "darkblue"),  # 4 color values for 4 categories
      name = "Ratio Category"  # Legend title
    ) +
    theme_minimal() +
    theme(legend.position = "right")

```

```{r}
ggplot(shps_sf) +
    geom_sf(aes(fill = coefPCTSINGLESst_cat), color = NA) +  # Use the categorized variable
    scale_fill_manual(
      values = c("darkred", "pink", "lightblue", "darkblue"),  # 4 color values for 4 categories
      name = "Ratio Category"  # Legend title
    ) +
    theme_minimal() +
    theme(legend.position = "right")

```

```{r}
ggplot(shps_sf) +
    geom_sf(aes(fill = coefPCTBACHMORst_cat), color = NA) +  # Use the categorized variable
    scale_fill_manual(
      values = c("darkred", "pink", "lightblue", "darkblue"),  # 4 color values for 4 categories
      name = "Ratio Category"  # Legend title
    ) +
    theme_minimal() +
    theme(legend.position = "right")
```

```{r}
ggplot(shps_sf) +
    geom_sf(aes(fill = coefLNNBELPOVst_cat), color = NA) +  # Use the categorized variable
    scale_fill_manual(
      values = c("darkred", "pink", "lightblue", "darkblue"),  # 4 color values for 4 categories
      name = "Ratio Category"  # Legend title
    ) +
    theme_minimal() +
    theme(legend.position = "right")
```


